### ISSUE TITLE
Setting VS Code Debugging for SciChart.js: breakpoints in VSCode/Chrome Dev Tool are not being hit

### ISSUE THREAD

**Issue by puremood2002** [ABTSoftware/SciChart.JS.Examples#14]
Hello

I am using vscode/chrome dev tool for debugging, after clicking a button which should trigger the breakpoint, the app continues without hitting the breakpoint, the breakpoints appear to be "unbound breakpoint", the output shows this after my app loaded, I wonder if this has anything to do with it. I was able to debug my app before converting it to typescript and using scichart.js

Or if you could provide a simple tutorials on how to do it? 

thanks a lot.

![vscode-breakpoint](https://user-images.githubusercontent.com/3439750/98599924-c46a0800-22aa-11eb-8ed0-4063ac231b30.png)

**Comment by klishevich** [comment]
Hi @puremood2002 this is a TypeScript boilerplate project for SciChart.js debugging in VS Code.

**Comment by puremood2002** [comment]
thanks I will give it a try
