### ISSUE TITLE
create-react-app with scichart 2.2.2378 not working

### ISSUE THREAD

**Issue by frankimhof** [ABTSoftware/SciChart.JS.Examples#155]
## setup
- Brave Version 1.39.111, Chromium: 102.0.5005.61
- `create-creact-app sci-try --template typescript` (React 18.1.0)
- `npm i scichart` (Scichart 2.2.2378)
- `npm i -D copy-files-from-to`
- a simple scichart as described in [demo-create-react-app](https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/demo-create-react-app-scichart) (with custom `wasmCopy` and `dev` scripts in `package.json`)

## code used
The code used can be found [here](https://github.com/frankimhof/sci-try). Don't forget to insert your license key.

## expectation
`npm run dev` will display the chart

## result
- a loading screen appears for a short time, then disappears
- When applying changes to`App.tsx` and saving, (dev server reload), the chart appears
- When reloading the page, the chart disappears again
- Console log shows no error messages

## observation
- using the same code but with scichart version `2.1.0-beta.40` works

**Comment by antichaosdb** [comment]
A bugfix related to this was just released.  Can you retry with latest 2.2.2397?

SciChart Ltd

**Comment by frankimhof** [comment]
> A bugfix related to this was just released. Can you retry with latest 2.2.2397?
> 
> SciChart Ltd

Test with version 2.2.2397 was successful.
Thanks.
