### ISSUE TITLE
Stacking of axis not working correctly in the new version as earlier

### ISSUE THREAD

**Issue by sakshamjaiswal1** [ABTSoftware/SciChart.JS.Examples#180]

**Comment by andyb1979** [comment]
Hi there, any further detail to help us diagnose or assist?

**Comment by sakshamjaiswal1** [comment]
scichart": "^2.2.2415"-- the version i am using 
and i have updated to the latest version that was releaed 12 days ago

**Comment by andyb1979** [comment]
This should work without changes.
I’ll try create a codepen later and see if I can reproduce it

**Comment by andyb1979** [comment]
OK with the information provided so far, I'm not able to reproduce this problem

Perhaps you can modify [this codepen here](https://codepen.io/scichart/pen/ExpewpP) until it shows the issue you're seeing?
<img width="1425" alt="Screenshot 2023-01-30 at 21 09 36" src="https://user-images.githubusercontent.com/14041557/215595774-cbc1aea0-2995-4d5b-acf1-9bcd4d0484eb.png">

**Comment by sakshamjaiswal1** [comment]
@andyb1979 Thnks a lot now the bug is fixed in the latest version
