### ISSUE TITLE
Using Scichart with create-react-app

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#20]
Hello guys!

I'm trying to set it up this lib on a `create-react-app`  is there any tutorial to set this library on it ?

Should I always use a custom project using webpack.config.js or can I rewrite the webpack config for one create-react-app project ? 

![image](https://user-images.githubusercontent.com/5354758/100300989-6ac53700-2f54-11eb-8c68-94b1548390dd.png)

![image](https://user-images.githubusercontent.com/5354758/100301037-86c8d880-2f54-11eb-9fe8-8e645f40b661.png)

**Comment by klishevich** [comment]
Hi @hecto932 we have a boilerplate project with Create React App. Please check it out - https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/demo-create-react-app-scichart

**Comment by hecto932** [comment]
Excellent! Thank you @klishevich
