### ISSUE TITLE
Getting XyDataSeries by Zoom applied

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#21]
Hi guys!

Do we have one method to get xyDataSeries base on some zoom state? 

![image](https://user-images.githubusercontent.com/5354758/101593562-5ef25f80-39ad-11eb-852b-6779732681b7.png)

For example:

I'm using RubberBandXyZoomModifier to make zoom on the chart, but i would like to get all of the points contained inside that area selected.

Is this possible?

**Comment by klishevich** [comment]
Hi @hecto932, isn't that how it works now?

**Comment by andyb1979** [comment]
Hi Hector - I think what you're asking for is

 1. Rubber band draw a rectangle but not zoom
 2. Get some kind of notification when the user stopped dragging the mouse 
 3. Get a list of all the data-points (x,y values) inside the rectangle

Answer: yes it is possible but I need to know exactly what you want to achieve before creating some sample code. 

Thanks!

**Comment by hecto932** [comment]
Hello @andyb1979.

Sorry for the confusion, but that is exactly what I'm looking for.

I would like to draw a rectangle without zoom on the chart and make a calculation to get all the data-points (x,y values) inside the rectangle

**Comment by klishevich** [comment]
Hi @hecto932 we created simple data selection example. Please find it here - https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/CustomerExamples/SimpleDataPointSelectionModifier

**Comment by hecto932** [comment]
Thank you @klishevich !

I'll take a look at it.

**Comment by andyb1979** [comment]
Thanks for the feature request @hecto932, Michael created a sample above - using our custom modifier API. The Custom ChartModifier API in scichart.js is very powerful and there's lots of behaviour mods you can create with it. Let us know if you need anything else! 

Best regards, 
Andrew
