### ISSUE TITLE
Using SciChart.js with react-app-rewired, customize-cra and Babel

### ISSUE THREAD

**Issue by umernawaz0301** [ABTSoftware/SciChart.JS.Examples#24]
We have a project, which Reactjs based, using react-app-rewired, customize-cra, and Babel (not webpack).

We want to use scichart in our project, but right now I'm facing difficulty, when i include SciChart into our project.

Can anyone please guide me on how should I do that? This is the issue I'm facing ATM

![image](https://user-images.githubusercontent.com/17135788/102364998-e9077d00-3fd8-11eb-9ddf-40a0f4fc62cb.png)

Thank you!

**Comment by andyb1979** [comment]
Hello!

If you can share us a project that reproduces this issue + some
instructions (as we are not familiar with Babel) our team will be happy to
investigate.

Best regards,
Andrew

**Comment by klishevich** [comment]
Hi @umernawaz0301 when adding SciChart.js into a project it is important to place `scichart2d.wasm` file in the same folder as the bundle.js file and `scichart2d.data` into the root folder. 
We have create-react-app example where we use copy-files-from-to to solve this problem (https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/demo-create-react-app-scichart).
In addition we have another example where we leverage copy-webpack-plugin (https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/demo-react-scichart).
Please take a look, and let me know if it helps.

**Comment by umernawaz0301** [comment]
Hello!

Sure @andyb1979, I will be more than happy to create a demo project for you guys.

@klishevich Thank you for the example links I will look into these as well

Thank you!
