### ISSUE TITLE
Point maker issues on LineSeries

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#26]
Hello guys, 

I'm working with Charts in both the orientations (horizontal and vertical by default), but I'm getting this weird behavior with the point makers on vertical mode.

![image](https://user-images.githubusercontent.com/5354758/103802886-10b49880-500d-11eb-9c78-dbd9554463e9.png)

Here are my initial settings to draw the sci chart surface

```
const draw = async (divElem: string, orientation: string = 'vertical', columns: Array<string> = [], data: Array<any> = []) => {
  
  SciChartSurface.setRuntimeLicenseKey(apiKey);

  const { sciChartSurface, wasmContext } = await SciChartSurface.create(divElem);

  const xAxis = new NumericAxis(wasmContext);
  const yAxis = new NumericAxis(wasmContext);

  xAxis.labelProvider.formatLabel = formatAxis;
  yAxis.labelProvider.formatLabel = numberToFix;

  // SET VERTICAL ORIENTATION BY DEFAULT
  xAxis.axisAlignment = EAxisAlignment.Left;
  yAxis.axisAlignment = EAxisAlignment.Bottom;

  // An axis may be optionally flipped using flippedCoordinates property
  yAxis.flippedCoordinates = true;

  // ADDING AXES TO SURFACE
  sciChartSurface.xAxes.add(xAxis);
  sciChartSurface.yAxes.add(yAxis);

  return { sciChartSurface, wasmContext };
};
```

Here are my settings for each line serie

```
const xyDataSeries = new XyDataSeries(wasmContext);
xyDataSeries.dataSeriesName = columnName;
const lineSeries = new FastLineRenderableSeries(wasmContext, {
  stroke: randomColor(),
  strokeThickness: 3,
  dataSeries: xyDataSeries,
  pointMarker: new EllipsePointMarker(wasmContext, {
    width: 5,
    height: 5,
    strokeThickness: 2,
    fill: 'white',
    stroke: 'white',
  }),
});
```

Do you have any idea about what I'm doing wrong when I'm switching between both orientations?

Can you provide me with some examples to have the Point markers for a line serie on Vertical Mode?

**Comment by andyb1979** [comment]
Hey Hector

It might be a bug. Is that code above enough to reproduce the problem in
full?

**Comment by hecto932** [comment]
Hey @andyb1979, thanks for your response.

Yes, that was what I thought. 

It might be enough to reproduce the problem

![image](https://user-images.githubusercontent.com/5354758/103807333-7c016900-5013-11eb-8e72-06c9d4c0228b.png)

Do you need anything else?

**Comment by klishevich** [comment]
Hi @hecto932 
We had a fix for this issue. Please make sure you are using the latest SciChart.js version 1.1.1362.

**Comment by hecto932** [comment]
Awesome guys!

Now, it's working :)

![image](https://user-images.githubusercontent.com/5354758/104034418-15548a80-518e-11eb-9c3c-39c81b3870ef.png)
