### ISSUE TITLE
Multicharting

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#28]
Hey guys, 

is it possible to have many scichart charts on the same screen? 

I'm looking to make something like this.

![image](https://user-images.githubusercontent.com/5354758/104955248-2455ec80-5987-11eb-9e49-f1326f25c337.png)

Do you have a similar example ?

**Comment by klishevich** [comment]
Hi @hecto932! Sure it is possible take a look at Audio Analyzer Demo it has 3 charts on one page - https://demo.scichart.com/javascript-audio-analyzer-fft-example , source code is here-
https://github.com/ABTSoftware/SciChart.JS.Examples/blob/master/Examples/src/components/Examples/FeaturedApps/ScientificCharts/AudioAnalyzer/index.tsx
Let me know if it helps!
