### ISSUE TITLE
Javascript: Uncaught Error: currentRenderPassData should not be undefined

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#55]
Hello scichart team,

I got this error when I'm testing this example

https://demo.scichart.com/javascript-chart-rollovermodifier-tooltips

![image](https://user-images.githubusercontent.com/5354758/110083126-8c03a380-7d4b-11eb-8cae-01533591c041.png)

It seems it happens when the chart is loading and I pass the cursor on the scichart surface component.

I can't remove and add new series on it.

**Comment by klishevich** [comment]
Hi @hecto932 thank you for creating the issue, we will look into it.

**Comment by klishevich** [comment]
Hi again @hecto932 :), please check out version 1.2.1473 containing the fix and let us know!

**Comment by hecto932** [comment]
Hi @klishevich 

I'll look into it!

Thanks
