### ISSUE TITLE
Touch devices: zoom

### ISSUE THREAD

**Issue by jwo** [ABTSoftware/SciChart.JS.Examples#63]
Is there an option to enable touch-devices zoom/pan? It works with a mouse and with a laptop touch screen, but if I view the Zoom/Pan example in an ipad, the zooming doesn't work how I expect it to. Instead, it zooms in on the page itself, not the chart instance.

![scichart](https://user-images.githubusercontent.com/123075/111361299-af87f180-865b-11eb-8fe7-bc186e21f7cf.gif)

Examples where this does with is d3-zoom and the plotly example: "setZoom: true"

**Comment by andyb1979** [comment]
Hey Jesse

Thanks for reporting, touch screen issues are on our work queue and
in-progress already (link to task here
https://abtsoftware.myjetbrains.com/youtrack/issue/SCJS-375) and we aim to
get them resolved soon.

Will notify you when we have an update!

Best regards,
Andrew

**Comment by jwo** [comment]
@andyb1979 perfect, thank you!

**Comment by observerjnr** [comment]
Hello Jesse,
You can set  `touch-action: none;` on the chart root element to prevent the default browser touch behavior.
That will allow the chart modifiers to respond properly...

https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by observerjnr** [comment]
Hello @jwo 
We have finally released the PinchZoomModifier feature.
Check out [this example](https://demo.scichart.com/zoom-pan-multiple-modifiers)

**Comment by jwo** [comment]
@observerjnr looks perfect! Great job. Thank you
