### ISSUE TITLE
Getting X and Y pair values when we get XyDataSeries by Zoom area

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#64]
Hello! 

Is there is any way to get the X and Y pair values when we create a box annotation? 

This issue is related to #21

**Comment by klishevich** [comment]
Hi @hecto932 if you need to get box coordinates out of RubberBandXyZoomModifier, you need to create you custom modifier extending RubberBandXyZoomModifier. Please take a look at this example, it shows how to extend chart modifiers - https://github.com/ABTSoftware/SciChart.JS.Examples/tree/master/Sandbox/CustomerExamples/RangeSelectionWithCustomModifier

**Comment by hecto932** [comment]
Awesome @klishevich!

 I'll look into it

**Comment by hecto932** [comment]
@klishevich 

Following that example above and trying to make something like #21, how can I get all the XYDataSeries by Range Selection on X-axis?

Do we have some method to test Bounds just in the X range?

**Comment by klishevich** [comment]
Hi @hecto932 take a look at Hit-Test API - https://demo.scichart.com/javascript-chart-hit-test-on-click
