### ISSUE TITLE
Issues with RolloverModifier

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#67]
Hi guys!

I'm adding the rolloverModifier to watch the values on the chart using the cursor and I'm getting this issue.

![image](https://user-images.githubusercontent.com/5354758/111857867-b5970000-88f1-11eb-9e00-4f7a3f8ffba3.png)

Also, I don't know if this is a bug, but I need to know when each modifier is being attached or detached, so when I comment on this code from the example, it works.

```
 const setTooltip = (resScichartSurface: SciChartSurface) => {
    const tooltipModifier = new RolloverModifier();

    // tooltipModifier.onDetach = () =>
      console.log(`${id}: tooltip rolloverModifier removed!`);
    // tooltipModifier.onAttach = () =>
      console.log(`${id}: tooltip rolloverModifier attached`);

    resScichartSurface.chartModifiers.add(tooltipModifier);
    setSciChartTooltip(tooltipModifier);
  };
```

I have a simple sample about this issue here.

https://github.com/hecto932/scichart-example-issue

Please don't hesitate to ask me if you have any doubt.

**Comment by klishevich** [comment]
Hi @hecto932! Because for some of the modifiers (for RolloverModifier) onAttach and onDetach methods are used internally we cannot just override them, we need to call super. Therefore, you should create a custom modifier like this:
```
class RollModifier2 extends RolloverModifier {
  private id: string;

  constructor(id: string, options?: IRolloverModifierOptions) {
    super();
    this.id = id;
  }

  onDetach() {
    super.onDetach();
    console.log(`${this.id}: tooltip rolloverModifier removed!`);
  }

  onAttach() {
    super.onAttach();
    console.log(`${this.id}: tooltip rolloverModifier attached!`);
  }
}
```

**Comment by hecto932** [comment]
Hi @klishevich! 

Thank you for the idea of creating a custom rollover modifier.

I don't know why, but I'm still getting the same issue trying to display the tooltip 

<img width="1674" alt="Screen Shot 2021-03-22 at 9 57 05 PM" src="https://user-images.githubusercontent.com/5354758/112096640-e9755e00-8b5b-11eb-9508-d7679788b7a9.png">

In that image, the tooltip has been added, but It isn't showing up. 

Do you have any idea about what is happening? 

I've updated the scichart repository using the custom rollover modifier.

**Comment by klishevich** [comment]
Hi @hecto932 the problem is this line `resScichartSurface.annotations.clear()`:

```
  const setAnnotations = (resScichartSurface: SciChartSurface) => {
    // resScichartSurface.annotations.clear();

    // ADD ANNOTATIONS
    annotations.forEach((item: IAnnotation) => {
      resScichartSurface.annotations.add(item);
    });
  };
```

When you call annotations.clear() it clears all the annotations including RolloverModifier VerticalLine annotation. Just remove this line and it will fix the issue.

**Comment by hecto932** [comment]
Hi @klishevich, thanks for your response.

Why is the rollover being affecting by this? 

Is it a bug?

Why should be the right way to delete all the annotations on the surface?

**Comment by andyb1979** [comment]
Hi Hector

Good point, we were discussing today how the annotation collections exposed
by the API should be separate to the annotations for modifiers (like the
rollover). This is how it is on other platforms of SciChart (Windows,
mobile).

We'll take a look at this and get back to you. In the meantime, does the
workaround work?

Best regards,
Andrew

**Comment by hecto932** [comment]
Hi @andyb1979, thanks for your response.

Yes, I think in the meantime this solution works for me.

Please, feel free to share with me any update about how you are going to handle the Annotations or Modifiers in the future

Regards!
