### ISSUE TITLE
 Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by hecto932** [ABTSoftware/SciChart.JS.Examples#78]
Currently, my scichart surface is having data changes fastly and when I call this function.
```
scichart.renderableSeries.clear();
``` 

![image](https://user-images.githubusercontent.com/5354758/113222600-3af8a980-923c-11eb-8ad1-0a62958636ea.png)

![image](https://user-images.githubusercontent.com/5354758/113222629-477d0200-923c-11eb-95ad-738925798a85.png)

![image](https://user-images.githubusercontent.com/5354758/113222656-5368c400-923c-11eb-8c84-d8af0b1fc9d3.png)

![image](https://user-images.githubusercontent.com/5354758/113222676-59f73b80-923c-11eb-8157-f4f366c646b6.png)

Do you have any idea about it?

**Comment by klishevich** [comment]
Hi @hecto932 could you please provide the source code to reproduce the error
