### ISSUE TITLE
Connect MQTT Endpoint to the Chart

### ISSUE THREAD

**Issue by Wahesh** [ABTSoftware/SciChart.JS.Examples#90]
Has anyone tried using the SciChart with MQTT Endpoint? I am trying to connect a MQTT Endpoint to the Chart and it has not been working so far. The Charts work pretty well when data is given in a file but when it is given in as MQTT endpoint, the charts are not shown. 
If there is a working Example of MQTT it would be nice.

**Comment by andyb1979** [comment]
Hi Wahesh, 

It's not really our responsibility to show how to connect to frameworks like MQTT, but yes, SciChart should theoretically work with any data-provider, data-base or streaming source of data. We provide samples that show how to create a SciChart chart and how to update it in realtime. There are a number of video tutorials over here which can be helpful for instance. 

[Tutorial 04 - Adding Realtime Updates](https://www.scichart.com/documentation/js/current/webframe.html#Tutorial%2004%20-%20Adding%20Realtime%20Updates.html)

<iframe width="560" height="315" src="https://www.youtube.com/embed/3TzRbpmx7T0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

What I can suggest is if you experience problems, provide a short code-sample that our team can run and we can provide guidance on how to make it work. 

Best regards, 
Andrew
