### ISSUE TITLE
Outiside labels for the SciChartPieSurface for .js

### ISSUE THREAD

**Issue by tielushko** [ABTSoftware/SciChart.JS.Examples#91]
I was looking over the documentation for the Pie Surface for JS and noticed that it does not have the outside label controls like the corresponding WPF surface does. I was wondering whether the team plans to release this improvement sometime in the future? I would appreciate your response!

**Comment by andyb1979** [comment]
Hi @tielushko , thanks for the comment, I'll feed this back to the tech team. If we haven't got hte feature we will add it to the roadmap. 

By the way, did you know there's a new forum over at[ scichart.com/questions](https://www.scichart.com/questions) where you can post Q's directly to our team? 

Best regards,
Andrew

**Comment by klishevich** [comment]
Hi @tielushko support for outside labels has been implemented in version 2.0, which will be released soon. Right now alpha version is published https://www.npmjs.com/package/scichart/v/2.0.0-alpha.2007 and CustomerExamples are updated for version 2.x https://github.com/ABTSoftware/SciChart.JS.Examples/tree/dev_v2.x/Sandbox/CustomerExamples
This is the commit with changes to update 1.x -> 2.x https://github.com/ABTSoftware/SciChart.JS.Examples/commit/2ce50bf424b2d9bd55365f566c36ad0d27ca380c
By the time of the release list of new features, breaking changes and documentation will be published

**Comment by tielushko** [comment]
Thanks for the update @klishevich! I ended up using a different pie chart, but sure will check out all the most recent updates to it!
