### ISSUE TITLE
fonts look pixelated

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [ABTSoftware/SciChart.JS.Examples#92]
really bad for a commercial charting solution. Design doesn't seem to matter for scichart? This is just one of countless other examples where design mistakes were made.  Look and feel is just really low with these charts.

![Screenshot 2021-06-16 at 23-18-14 LiDAR 3D Point Cloud of Geospatial Data JavaScript Chart Examples](https://user-images.githubusercontent.com/45887282/122307083-294ca700-cef9-11eb-8661-bd8185746c10.png)

**Comment by hp8wvvvgnj6asjm7** [comment]
... no comment.. 
please fix this.
speechless to how much carelessness was put into this. 

![Screenshot 2021-06-16 at 23-25-17 Chart Legends API JavaScript Chart Examples](https://user-images.githubusercontent.com/45887282/122307590-28684500-cefa-11eb-99b1-b9569ebedb65.png)

**Comment by andyb1979** [comment]
I take your point about the 3d chart text, but not sure what the problem with the legend is? 

3D Chart in SciChart.js uses a font-generation library called [FreeType](https://www.freetype.org/). Text rendering is notoriously difficult in 3d graphics! Nevertheless we aim for high quality across platforms so your complaint is duly noted

Best regards, 
Andrew

**Comment by hp8wvvvgnj6asjm7** [comment]
re: legend

Bad spacing. Checkbox goes against the scichart theme ( if we can call it a theme at all ). 
- Font is too big.
- Checkbox too close to the colored box.
- First line's font is bigger than the rest ( yes it may have been intentional, but there are other ways to emphasis something **BOLD** anyone? )

**Comment by hp8wvvvgnj6asjm7** [comment]
If you can't see this, who is in chart of the UI / UX ?

**Comment by hp8wvvvgnj6asjm7** [comment]
If you can't see this, who is in charge of the UI / UX ?

**Comment by hp8wvvvgnj6asjm7** [comment]
Btw glowing lines on a chart is what nobody asked for. It looks like early era of flash websites, why are we continuing this?

**Comment by hp8wvvvgnj6asjm7** [comment]
Your charts all feel soft and about to melt. Font's are placed badly. It just feels like a toy.

**Comment by hp8wvvvgnj6asjm7** [comment]
scichart website has also many many design issues, don't even know where to start.. 
How the logo doesn't fit in? How the magnifying glass looks cheap? How the way the font is used is a complete nightmare?

This is good design: https://www.terra.money/

this is bad design: https://www.scichart.com/

similar font. different worlds.

**Comment by hp8wvvvgnj6asjm7** [comment]
I hover over your navigation and what does my mouse cursor do? Shows a text selection cursor.

**Comment by andyb1979** [comment]
The entire legend is customisable, if you want to change it’s pretty simple! Take a look at the Legend Modifier docs. If you have a tech question you can also ask it like “how do I customise the legend to fit with my theme”

We’re pretty transparent here at SciChart and we welcome constructive criticism, but if your plan is to get attention by being rude to me or my staff, you’re not going to get much response… Try to be more constructive or I’ll have to block you permanently from the repo,

Best regards
Andrew

**Comment by hp8wvvvgnj6asjm7** [comment]
F U C K ! Y O U !

**Comment by andyb1979** [comment]
Alright good bye now, have a nice evening & weekend wherever you are

**Comment by andyb1979** [comment]
_OP: "really bad for a commercial charting solution. Design doesn't seem to matter for scichart?"_

Never underestimate someone who continually improves

![image](https://user-images.githubusercontent.com/14041557/222522971-faccf531-642d-4909-bdcb-7c68773fbcfa.png)

See more demos at https://www.scichart.com/examples/javascript-chart/
